-- MySQL Script generated by MySQL Workbench
-- Thu Aug 23 20:26:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Usuario` (
  `idTipo_Usuario` INT NOT NULL,
  `Tipo_Usuario` VARCHAR(45) NULL,
  `Fecha_Registro` DATETIME NULL,
  `Tipo_Usuariocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `Tipo_Usuario_idTipo_Usuario` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`, `Tipo_Usuario_idTipo_Usuario`),
  INDEX `fk_Usuarios_Tipo_Usuario1_idx` (`Tipo_Usuario_idTipo_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Tipo_Usuario1`
    FOREIGN KEY (`Tipo_Usuario_idTipo_Usuario`)
    REFERENCES `mydb`.`Tipo_Usuario` (`idTipo_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoEstudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoEstudio` (
  `idTipoEstudio` INT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoEstudio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudios` (
  `idEstudios` INT NOT NULL,
  `fechaInicio` DATE NULL,
  `fechaTerm/cont` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `nombreInstitucion` VARCHAR(45) NULL,
  `TipoEstudio_idTipoEstudio` INT NOT NULL,
  PRIMARY KEY (`idEstudios`, `TipoEstudio_idTipoEstudio`),
  INDEX `fk_Estudios_TipoEstudio1_idx` (`TipoEstudio_idTipoEstudio` ASC) VISIBLE,
  CONSTRAINT `fk_Estudios_TipoEstudio1`
    FOREIGN KEY (`TipoEstudio_idTipoEstudio`)
    REFERENCES `mydb`.`TipoEstudio` (`idTipoEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ciudad` (
  `idCiudad` INT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idCiudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReferenciasProfesionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReferenciasProfesionales` (
  `idReferenciasProfesionales` INT NULL,
  `nombreEmpresa` VARCHAR(45) NULL,
  `años` INT NULL,
  `cargo` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`idReferenciasProfesionales`, `Ciudad_idCiudad`),
  INDEX `fk_ReferenciasProfesionales_Ciudad1_idx` (`Ciudad_idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_ReferenciasProfesionales_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `mydb`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoEcivil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoEcivil` (
  `idTipoEcivil` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoEcivil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoDocumento` (
  `idTipoDocumento` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DatosPersonales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DatosPersonales` (
  `idDatosPersonales` INT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono1` INT NULL,
  `telefono2` INT NULL,
  `correoElectronico` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `numeroDocumento` VARCHAR(45) NULL,
  `TipoEcivil_idTipoEcivil` INT NOT NULL,
  `TipoDocumento_idTipoDocumento` INT NOT NULL,
  `CiudadNacimiento_idCiudad` INT NOT NULL,
  `Fecha_Nacimiento` DATETIME NULL,
  `CiudadExpDoc_idCiudad` INT NOT NULL,
  `DatosPersonalescol` VARCHAR(45) NULL,
  PRIMARY KEY (`idDatosPersonales`, `TipoEcivil_idTipoEcivil`, `TipoDocumento_idTipoDocumento`, `CiudadNacimiento_idCiudad`, `CiudadExpDoc_idCiudad`),
  INDEX `fk_DatosPersonales_TipoEcivil1_idx` (`TipoEcivil_idTipoEcivil` ASC) VISIBLE,
  INDEX `fk_DatosPersonales_TipoDocumento1_idx` (`TipoDocumento_idTipoDocumento` ASC) VISIBLE,
  INDEX `fk_DatosPersonales_Ciudad1_idx` (`CiudadNacimiento_idCiudad` ASC) VISIBLE,
  INDEX `fk_DatosPersonales_cuidad2_idx` (`CiudadExpDoc_idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_DatosPersonales_TipoEcivil1`
    FOREIGN KEY (`TipoEcivil_idTipoEcivil`)
    REFERENCES `mydb`.`TipoEcivil` (`idTipoEcivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DatosPersonales_TipoDocumento1`
    FOREIGN KEY (`TipoDocumento_idTipoDocumento`)
    REFERENCES `mydb`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DatosPersonales_Ciudad1`
    FOREIGN KEY (`CiudadNacimiento_idCiudad`)
    REFERENCES `mydb`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DatosPersonales_cuidad2`
    FOREIGN KEY (`CiudadExpDoc_idCiudad`)
    REFERENCES `mydb`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HojaVida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HojaVida` (
  `idHojaVida` INT NOT NULL,
  `Estudios_idEstudios` INT NOT NULL,
  `ReferenciasProfesionales_idReferenciasProfesionales` INT NOT NULL,
  `DatosPersonales_idDatosPersonales` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Usuarios_trabajo_idtrabajo` INT NOT NULL,
  `Usuarios_Tipo_Usuario_idTipo_Usuario` INT NOT NULL,
  PRIMARY KEY (`idHojaVida`, `Estudios_idEstudios`, `ReferenciasProfesionales_idReferenciasProfesionales`, `DatosPersonales_idDatosPersonales`),
  INDEX `fk_HojaVida_Estudios1_idx` (`Estudios_idEstudios` ASC) VISIBLE,
  INDEX `fk_HojaVida_ReferenciasProfesionales1_idx` (`ReferenciasProfesionales_idReferenciasProfesionales` ASC) VISIBLE,
  INDEX `fk_HojaVida_DatosPersonales1_idx` (`DatosPersonales_idDatosPersonales` ASC) VISIBLE,
  INDEX `fk_HojaVida_Usuarios1_idx` (`Usuarios_idUsuarios` ASC, `Usuarios_trabajo_idtrabajo` ASC, `Usuarios_Tipo_Usuario_idTipo_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_HojaVida_Estudios1`
    FOREIGN KEY (`Estudios_idEstudios`)
    REFERENCES `mydb`.`Estudios` (`idEstudios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HojaVida_ReferenciasProfesionales1`
    FOREIGN KEY (`ReferenciasProfesionales_idReferenciasProfesionales`)
    REFERENCES `mydb`.`ReferenciasProfesionales` (`idReferenciasProfesionales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HojaVida_DatosPersonales1`
    FOREIGN KEY (`DatosPersonales_idDatosPersonales`)
    REFERENCES `mydb`.`DatosPersonales` (`idDatosPersonales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HojaVida_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios` , `Usuarios_Tipo_Usuario_idTipo_Usuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios` , `Tipo_Usuario_idTipo_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Areo_Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Areo_Cargo` (
  `idAreo_Cargo` INT NOT NULL,
  `Areo_Cargo` VARCHAR(45) NULL,
  `Areo_Cargocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idAreo_Cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Experiencia_Laborales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Experiencia_Laborales` (
  `idtrabajo` INT NULL,
  `sueldo` INT NULL,
  `fechaInicio` DATE NULL,
  `fecha terminacio/cont` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  `Administrador_Usuarios_idUsuarios` INT NOT NULL,
  `DatosPersonales_idDatosPersonales` INT NOT NULL,
  `DatosPersonales_TipoEcivil_idTipoEcivil` INT NOT NULL,
  `DatosPersonales_TipoDocumento_idTipoDocumento` INT NOT NULL,
  `DatosPersonales_CiudadNacimiento_idCiudad` INT NOT NULL,
  `DatosPersonales_CiudadExpDoc_idCiudad` INT NOT NULL,
  `Areo_Cargo_idAreo_Cargo` INT NOT NULL,
  PRIMARY KEY (`idtrabajo`, `Administrador_idAdministrador`, `Administrador_Usuarios_idUsuarios`, `Areo_Cargo_idAreo_Cargo`),
  INDEX `fk_Experiencia_Laborales_DatosPersonales1_idx` (`DatosPersonales_idDatosPersonales` ASC, `DatosPersonales_TipoEcivil_idTipoEcivil` ASC, `DatosPersonales_TipoDocumento_idTipoDocumento` ASC, `DatosPersonales_CiudadNacimiento_idCiudad` ASC, `DatosPersonales_CiudadExpDoc_idCiudad` ASC) VISIBLE,
  INDEX `fk_Experiencia_Laborales_Areo_Cargo1_idx` (`Areo_Cargo_idAreo_Cargo` ASC) VISIBLE,
  CONSTRAINT `fk_Experiencia_Laborales_DatosPersonales1`
    FOREIGN KEY (`DatosPersonales_idDatosPersonales` , `DatosPersonales_TipoEcivil_idTipoEcivil` , `DatosPersonales_TipoDocumento_idTipoDocumento` , `DatosPersonales_CiudadNacimiento_idCiudad` , `DatosPersonales_CiudadExpDoc_idCiudad`)
    REFERENCES `mydb`.`DatosPersonales` (`idDatosPersonales` , `TipoEcivil_idTipoEcivil` , `TipoDocumento_idTipoDocumento` , `CiudadNacimiento_idCiudad` , `CiudadExpDoc_idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Experiencia_Laborales_Areo_Cargo1`
    FOREIGN KEY (`Areo_Cargo_idAreo_Cargo`)
    REFERENCES `mydb`.`Areo_Cargo` (`idAreo_Cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoEstudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoEstudio` (
  `idTipoEstudio` INT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoEstudio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoIdioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoIdioma` (
  `idTipoIdioma` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoIdioma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Idiomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Idiomas` (
  `idIdiomas` INT NOT NULL,
  `institucion` VARCHAR(45) NULL,
  `TipoIdioma_idTipoIdioma` INT NOT NULL,
  `Estudios_idEstudios` INT NOT NULL,
  `Estudios_TipoEstudio_idTipoEstudio` INT NOT NULL,
  PRIMARY KEY (`idIdiomas`, `TipoIdioma_idTipoIdioma`),
  INDEX `fk_Idiomas_TipoIdioma1_idx` (`TipoIdioma_idTipoIdioma` ASC) VISIBLE,
  INDEX `fk_Idiomas_Estudios1_idx` (`Estudios_idEstudios` ASC, `Estudios_TipoEstudio_idTipoEstudio` ASC) VISIBLE,
  CONSTRAINT `fk_Idiomas_TipoIdioma1`
    FOREIGN KEY (`TipoIdioma_idTipoIdioma`)
    REFERENCES `mydb`.`TipoIdioma` (`idTipoIdioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idiomas_Estudios1`
    FOREIGN KEY (`Estudios_idEstudios` , `Estudios_TipoEstudio_idTipoEstudio`)
    REFERENCES `mydb`.`Estudios` (`idEstudios` , `TipoEstudio_idTipoEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nivel` (
  `idNivel` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Idiomas_idIdiomas` INT NOT NULL,
  `Idiomas_TipoIdioma_idTipoIdioma` INT NOT NULL,
  PRIMARY KEY (`idNivel`),
  INDEX `fk_Nivel_Idiomas1_idx` (`Idiomas_idIdiomas` ASC, `Idiomas_TipoIdioma_idTipoIdioma` ASC) VISIBLE,
  CONSTRAINT `fk_Nivel_Idiomas1`
    FOREIGN KEY (`Idiomas_idIdiomas` , `Idiomas_TipoIdioma_idTipoIdioma`)
    REFERENCES `mydb`.`Idiomas` (`idIdiomas` , `TipoIdioma_idTipoIdioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresas` (
  `idEmpresas` INT NOT NULL,
  `Empresa` VARCHAR(45) NULL,
  `Nit` INT NULL,
  `Fecha_Registro` DATETIME NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Usuarios_trabajo_idtrabajo` INT NOT NULL,
  `Usuarios_Tipo_Usuario_idTipo_Usuario` INT NOT NULL,
  PRIMARY KEY (`idEmpresas`),
  INDEX `fk_Empresas_Usuarios1_idx` (`Usuarios_idUsuarios` ASC, `Usuarios_trabajo_idtrabajo` ASC, `Usuarios_Tipo_Usuario_idTipo_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Empresas_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios` , `Usuarios_Tipo_Usuario_idTipo_Usuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios` , `Tipo_Usuario_idTipo_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ofertas Laborales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ofertas Laborales` (
  `idOfertasLaborales` INT NOT NULL,
  `Ofertas Laborales` VARCHAR(45) NULL,
  `Fecha_inicio` DATETIME NULL,
  `Fecha_cierre` DATETIME NULL,
  `TipoContrato` VARCHAR(45) NULL,
  `NumVacantes` INT NULL,
  `Oferta_Salarial` FLOAT NULL,
  `Años_Experiencia` INT NULL,
  `Ofertas Laboralescol` VARCHAR(45) NULL,
  `Empresas_idEmpresas` INT NOT NULL,
  `Areo_Cargo_idAreo_Cargo` INT NOT NULL,
  PRIMARY KEY (`idOfertasLaborales`, `Empresas_idEmpresas`, `Areo_Cargo_idAreo_Cargo`),
  INDEX `fk_Ofertas Laborales_Empresas1_idx` (`Empresas_idEmpresas` ASC) VISIBLE,
  INDEX `fk_Ofertas Laborales_Areo_Cargo1_idx` (`Areo_Cargo_idAreo_Cargo` ASC) VISIBLE,
  CONSTRAINT `fk_Ofertas Laborales_Empresas1`
    FOREIGN KEY (`Empresas_idEmpresas`)
    REFERENCES `mydb`.`Empresas` (`idEmpresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ofertas Laborales_Areo_Cargo1`
    FOREIGN KEY (`Areo_Cargo_idAreo_Cargo`)
    REFERENCES `mydb`.`Areo_Cargo` (`idAreo_Cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
